---
- name: Create Telegraf config file
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_configuration_dir }}/telegraf.conf"
  # If config changes, restart telegraf and confirm it remained running
  notify:
    - "restart telegraf"
    - "pause"
    - "check status"
    - "assert running"
