---
- name: Create Telegraf config file
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_configuration_dir }}/telegraf.conf"
  # If config changes, restart telegraf and confirm it remained running
  notify:
    - "restart telegraf"
    - "wait for startup"
    - "check status"

- name: Register telegraf deamon to start on bootup
  service:
    name: telegraf
    enabled: yes
